name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew mgrs:build -x lint
    - name: Copy Release Artifacts
      run: |
        mkdir mgrs/build/release
        cp mgrs/build/libs/*.jar mgrs/build/outputs/aar/*release.aar mgrs/build/release/
        grep "version =" mgrs/build.gradle | sed 's/[a-z ="]//g' > VERSION
        mv mgrs/build/release/*.aar mgrs/build/release/mgrs-android-$(cat VERSION).aar
    - name: Build App with Gradle
      run: ./gradlew app:assembleRelease -PRELEASE_MAPS_MGRS_API_KEY=${{ secrets.RELEASE_MAPS_MGRS_API_KEY }}
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Copy Release Artifacts
      run: |
        grep "version =" mgrs/build.gradle | sed 's/[a-z ="]//g' > VERSION
        cp app/build/outputs/apk/release/app-*-signed.apk "mgrs/build/release/mgrs-$(cat VERSION).apk"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mgrs-android
        path: mgrs/build/release
