name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build -x lint
    - name: Copy Release Artifacts
      run: |
        mkdir mgrs/build/release
        cp mgrs/build/libs/*.jar mgrs/build/outputs/aar/*release.aar mgrs/build/release/
        grep "version =" mgrs/build.gradle | sed 's/[a-z ="]//g' > VERSION
        mv mgrs/build/release/*.aar mgrs/build/release/mgrs-android-$(cat VERSION).aar
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mgrs-android
        path: mgrs/build/release
